### PR TITLE
Suggestion: Change due date to 11:59 PM :alarm_clock:

### PR DESCRIPTION
**Pull request by katamaritaco**
It is a lot less ambiguous and won't generate a million :pizza: (Piazza) posts that say "IS IT MIDNIGHT ON SUNDAY OR MONDAY?!?!?!

:alarm_clock::alarm_clock::alarm_clock::alarm_clock::alarm_clock::alarm_clock:

### CODE REVIEW

**Comment by ace0** [comment]
Excellent suggestion. Thank you.

**Comment by katamaritaco** [comment]
That feel when PR isn't integrated but change is made :sob: :sob: :sob: :sob:

**Comment by ace0** [comment]
image

**Comment by katamaritaco** [comment]
bless_you_my_child

**Pull request merged**
